/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JatoStyle.gui;

import JatoStyle.models.Restoran;
import JatoStyle.services.AuthService;
import java.awt.*;
import javax.swing.*;
import java.sql.ResultSet;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.DefaultTableCellRenderer;
import java.text.SimpleDateFormat;
import JatoStyle.models.TransactionDetail;
import JatoStyle.services.TransactionService;
import java.util.List;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JDialog;

public class DashboardRestoranFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardRestoranFrame.class.getName());

    private Restoran currentRestoran;
    private JPanel menuContainer;
    private JPanel transaksiContainer;
    private JPanel wrapper;
    private JScrollPane scrollPane;
    private JScrollPane transaksiScrollPane;
    private AuthService auth = new AuthService();
    private DefaultTableModel transaksiTableModel;
    private JTable transaksiTable;

    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel headerTitle;
    
    private TransactionService transactionService = new TransactionService(); // TAMBAHKAN INI

    public DashboardRestoranFrame(Restoran restoran) {
        this.currentRestoran = restoran;
        initComponents();
        setLocationRelativeTo(null);
        setupUI();
        loadMenuFromDatabase();    // load data
        loadTransaksiFromDatabase(); // load transaksi
    }
    
    // jika tidak sengaja panggil default ctor
    public DashboardRestoranFrame() {
        super("Dashboard Restoran");
        JOptionPane.showMessageDialog(this,
            "Frame ini membutuhkan data restoran untuk dibuka!",
            "Error", JOptionPane.ERROR_MESSAGE);
        dispose();
    }
    
    private void setupUI() {
        applyTemplateStyles();
        initDynamicUI();
        applyTabbedPaneStyle();
        headerTitle.setText("Data Restoran " + currentRestoran.getNamaRestoran());
    }

    /**
     * Creates new form DashboardRestoranFrame
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor
     */
    @SuppressWarnings("unchecked")
    
    private void initComponents() {
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(900, 600);
        setLocationRelativeTo(null);

        jTabbedPane = new JTabbedPane();
        mainPanel = new JPanel(new BorderLayout());
        logoLabel = new JLabel(new ImageIcon(getClass().getResource("/JatoStyle/gui/dashboardlogo.png")));
        headerTitle = new JLabel("Data Restoran " + currentRestoran.getNamaRestoran());
        logoutButton = new JButton("Logout");
    }

    
    private void applyTemplateStyles() {
        getContentPane().setBackground(new Color(250, 240, 227)); // #FAF0E3
        setTitle("Dashboard Restoran - " + (currentRestoran != null ? currentRestoran.getNamaRestoran() : ""));
        setLayout(new BorderLayout());
    }
    
    private void applyTabbedPaneStyle() {
        jTabbedPane.setUI(new javax.swing.plaf.basic.BasicTabbedPaneUI() {

            @Override
            protected void paintTabBackground(Graphics g, int tabPlacement, int tabIndex,
                                              int x, int y, int w, int h, boolean isSelected) {

                Graphics2D g2d = (Graphics2D) g.create();
                g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

                if (isSelected) {
                    g2d.setColor(new Color(241, 124, 42)); // orange
                } else {
                    g2d.setColor(new Color(250, 240, 227)); // cream
                }

                int margin = 8;
                int leftMargin = 15;
                int tabHeight = h - margin;
                int tabWidth = w - 10;

                g2d.fillRoundRect(x + leftMargin, y + margin, tabWidth, tabHeight, 15, 15);
                g2d.dispose();
            }

            @Override
            protected void paintTabBorder(Graphics g, int tabPlacement, int tabIndex, 
                                        int x, int y, int w, int h, boolean isSelected) {
                Graphics2D g2d = (Graphics2D) g.create();
                g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

                if (isSelected) {
                    g2d.setColor(new Color(229, 75, 31)); // #E54B1F
                } else {
                    g2d.setColor(new Color(200, 200, 200)); // abu-abu muda untuk tab tidak aktif
                }

                int margin = 8; // jarak antar tab 
                int leftMargin = 15; // geser ke kanan
                int tabHeight = h - margin; // tinggi tab
                int tabWidth = w - 10; // lebar tab
                g2d.drawRoundRect(x + leftMargin, y + margin, tabWidth, tabHeight, 15, 15);
                g2d.dispose();
            }
            
            @Override
            protected void paintFocusIndicator(Graphics g, int tabPlacement, Rectangle[] rects,
                                               int tabIndex, Rectangle iconRect, Rectangle textRect,
                                               boolean isSelected) {
            }

            @Override
            protected int getTabRunIndent(int tabPlacement, int run) {
                return 15; // indentasi utk geser tab ke atas
            }

            @Override
            protected Insets getTabAreaInsets(int tabPlacement) {
                return new Insets(15, 10, 0, 0);
            }

            @Override
            protected Insets getContentBorderInsets(int tabPlacement) {
                return new Insets(5, 0, 0, 0); // top, left, bottom, right
            }

            @Override
            protected int calculateTabWidth(int tabPlacement, int tabIndex, FontMetrics metrics) {
                return super.calculateTabWidth(tabPlacement, tabIndex, metrics) + 30; // tambah 30px lebar tab
            }

            @Override
            protected int calculateTabHeight(int tabPlacement, int tabIndex, int fontHeight) {
                return super.calculateTabHeight(tabPlacement, tabIndex, fontHeight) + 15; // tambah 15px tinggi tab
            }

        });

        jTabbedPane.setFont(new Font("Bahnschrift", Font.BOLD, 12));
        jTabbedPane.setForeground(new Color(59, 31, 11)); 
        jTabbedPane.setBackground(new Color(250, 240, 227));
        jTabbedPane.setBorder(BorderFactory.createLineBorder(new Color(229, 75, 31), 1));
    }
    
    private void initDynamicUI() {
        JPanel wrapper = new JPanel();
        wrapper.setLayout(new BorderLayout());
        wrapper.setBorder(new EmptyBorder(25, 30, 25, 30)); // kiri-kanan 30px, atas-bawah 25px
        wrapper.setOpaque(false);
        
        // HEADER
        JPanel headerPanel = new JPanel(new BorderLayout());
        headerPanel.setBackground(new Color(250, 240, 227));
        headerPanel.setBorder(new EmptyBorder(12, 20, 12, 20));

        // logo di kiri atas
        JPanel left = new JPanel(new FlowLayout(FlowLayout.LEFT, 0, 0));
        left.setOpaque(false);
        left.add(logoLabel);

        // title center
        JPanel center = new JPanel();
        center.setOpaque(false);
        headerTitle.setFont(new Font("Bahnschrift", Font.BOLD, 20));
        headerTitle.setForeground(new Color(59, 31, 11));
        center.add(headerTitle);

        // logout right (no profile)
        logoutButton.setBackground(new Color(229, 75, 31));
        logoutButton.setForeground(Color.WHITE);
        logoutButton.setFocusPainted(false);
        logoutButton.setBorder(new EmptyBorder(8, 15, 8, 15));
        logoutButton.addActionListener(e -> {
            int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin logout?", "Konfirmasi Logout", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                this.dispose();
                new LoginFrame().setVisible(true);
            }
        });
        JPanel right = new JPanel(new FlowLayout(FlowLayout.RIGHT, 0, 0));
        right.setOpaque(false);
        
        right.add(logoutButton);
        headerPanel.add(left, BorderLayout.WEST);
        headerPanel.add(center, BorderLayout.CENTER);
        headerPanel.add(right, BorderLayout.EAST);

        wrapper.add(headerPanel, BorderLayout.NORTH);

        // tabbed pane
        jTabbedPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane.setTabLayoutPolicy(JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane.setFont(new Font("Bahnschrift", Font.BOLD, 12));
        jTabbedPane.setBackground(new Color(250, 240, 227));
        jTabbedPane.setForeground(new Color(59, 31, 11));
        jTabbedPane.setBorder(BorderFactory.createLineBorder(new Color(229, 75, 31), 1));

        // tab 1 = Menu
        JPanel tabMenu = new JPanel(new BorderLayout());
        tabMenu.setBackground(new Color(250, 240, 227));
        jTabbedPane.addTab("Menu", tabMenu);

        // tab 2 = Transaksi
        JPanel tabTransaksi = new JPanel(new BorderLayout());
        tabTransaksi.setBackground(new Color(250, 240, 227));
        jTabbedPane.addTab("Transaksi", tabTransaksi);

        wrapper.add(jTabbedPane, BorderLayout.CENTER);
        add(wrapper, BorderLayout.CENTER);

        // UI list menu
        menuContainer = new JPanel();
        menuContainer.setBackground(new Color(250, 240, 227));
        menuContainer.setLayout(new BoxLayout(menuContainer, BoxLayout.Y_AXIS));
        menuContainer.setBorder(new EmptyBorder(15, 15, 15, 15));

        scrollPane = new JScrollPane(menuContainer);
        scrollPane.setBorder(null);
        scrollPane.getViewport().setBackground(new Color(250, 240, 227));
        JScrollBar vBar = scrollPane.getVerticalScrollBar();
        vBar.setUnitIncrement(16);

        tabMenu.add(scrollPane, BorderLayout.CENTER);

        // bottom panel dgn "Tambah Menu +"
        JPanel bottomPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        bottomPanel.setBackground(new Color(250, 240, 227));
        JButton addBtn = new JButton("Tambah Menu +");
        addBtn.setBackground(new Color(241, 124, 42)); // #F17C2A
        addBtn.setForeground(Color.WHITE);
        addBtn.setFocusPainted(false);
        addBtn.setBorder(new EmptyBorder(10, 20, 10, 20));
        addBtn.addActionListener(e -> openTambahMenuFrame());
        bottomPanel.add(addBtn);
        // put bottom panel into tabMenu south
        tabMenu.add(bottomPanel, BorderLayout.SOUTH);

        // UI panel transaction
        setupTransactionPanel(tabTransaksi);
    }

    private void setupTransactionPanel(JPanel tabTransaksi) {
        // table model
        String[] columnNames = {"ID Pesanan", "Tanggal", "Customer", "Total", "Status", "Aksi", "Detail"};
        transaksiTableModel = new DefaultTableModel(columnNames, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 5 || column == 6;
            }
        };

        // table
        transaksiTable = new JTable(transaksiTableModel) {
            @Override
            public Component prepareRenderer(javax.swing.table.TableCellRenderer renderer, int row, int column) {
                Component c = super.prepareRenderer(renderer, row, column);

                // warna baris bergantian
                if (!isRowSelected(row)) {
                    if (row % 2 == 0) {
                        c.setBackground(new Color(250, 240, 227)); // cream
                    } else {
                        c.setBackground(Color.WHITE);
                    }
                }

                // styling kolom status - TAMBAHKAN PENANGANAN UNTUK ROW YANG DIPILIH
                if (column == 4) {
                    String status = getValueAt(row, column).toString();
                    if (c instanceof JLabel) {
                        JLabel label = (JLabel) c;
                        label.setOpaque(true);
                        label.setHorizontalAlignment(SwingConstants.CENTER);

                        // Tentukan warna font berdasarkan apakah row dipilih
                        Color fontColor = isRowSelected(row) ? 
                            new Color(59, 31, 11) : // Hitam saat dipilih
                            Color.WHITE; // Putih saat tidak dipilih

                        switch (status.toUpperCase()) {
                            case "PENDING":
                            case "SEDANG DIBUAT":
                                label.setBackground(new Color(255, 193, 7)); // kuning
                                label.setForeground(isRowSelected(row) ? new Color(59, 31, 11) : Color.BLACK);
                                break;
                            case "SEDANG DIANTAR":
                                label.setBackground(new Color(33, 150, 243)); // biru
                                label.setForeground(fontColor);
                                break;
                            case "SUDAH SAMPAI":
                                label.setBackground(new Color(76, 175, 80)); // hijau
                                label.setForeground(fontColor);
                                break;
                            default:
                                label.setBackground(new Color(189, 189, 189)); // abu-abu
                                label.setForeground(fontColor);
                        }
                    }
                }

                // styling kolom aksi
                if (column == 5) {
                    if (c instanceof JLabel) {
                        JLabel label = (JLabel) c;
                        label.setHorizontalAlignment(SwingConstants.CENTER);
                        label.setForeground(new Color(33, 150, 243)); // Biru
                        label.setFont(new Font("Bahnschrift", Font.BOLD, 11));
                    }
                }

                // styling kolom detail
                if (column == 6) {
                    if (c instanceof JLabel) {
                        JLabel label = (JLabel) c;
                        label.setHorizontalAlignment(SwingConstants.CENTER);
                        label.setForeground(new Color(229, 75, 31)); // Oranye
                        label.setFont(new Font("Bahnschrift", Font.BOLD, 11));
                    }
                }

                return c;
            }
        };

        transaksiTable.setFont(new Font("Bahnschrift", Font.PLAIN, 12));
        transaksiTable.setRowHeight(50);
        transaksiTable.setBackground(new Color(250, 240, 227));

        // ========== INI YANG PENTING ==========
        // Atur warna selection - warna font TETAP HITAM saat dipilih
        transaksiTable.setSelectionBackground(new Color(241, 124, 42)); // Orange untuk background
        transaksiTable.setSelectionForeground(Color.BLACK); // Font tetap hitam

        // Juga atur untuk mencegah perubahan warna default
        transaksiTable.setForeground(new Color(59, 31, 11)); // Default font color hitam
        // ======================================

        // center alignment utk semua kolom
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        // Atur juga foreground untuk renderer
        centerRenderer.setForeground(new Color(59, 31, 11));

        for (int i = 0; i < transaksiTable.getColumnCount(); i++) {
            if (i != 2) { // Kecuali kolom Customer
                DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
                renderer.setHorizontalAlignment(SwingConstants.CENTER);
                renderer.setForeground(new Color(59, 31, 11)); // Warna font hitam
                transaksiTable.getColumnModel().getColumn(i).setCellRenderer(renderer);
            }
        }

        // Untuk kolom Customer (kolom 2), tetap left alignment
        DefaultTableCellRenderer leftRenderer = new DefaultTableCellRenderer();
        leftRenderer.setHorizontalAlignment(SwingConstants.LEFT);
        leftRenderer.setForeground(new Color(59, 31, 11)); // Warna font hitam
        transaksiTable.getColumnModel().getColumn(2).setCellRenderer(leftRenderer);

        // mouse listener untuk handle klik pada kolom aksi dan detail
        setupTableMouseListener();

        // styling header
        JTableHeader header = transaksiTable.getTableHeader();
        header.setFont(new Font("Bahnschrift", Font.BOLD, 13));
        header.setBackground(new Color(241, 124, 42));
        header.setForeground(Color.WHITE);
        header.setReorderingAllowed(false);

        // setup scroll pane
        transaksiScrollPane = new JScrollPane(transaksiTable);
        transaksiScrollPane.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(new Color(229, 75, 31), 2),
            BorderFactory.createEmptyBorder(10, 10, 10, 10)
        ));
        transaksiScrollPane.getViewport().setBackground(new Color(250, 240, 227));

        tabTransaksi.add(transaksiScrollPane, BorderLayout.CENTER);
    }

    private void setupTableMouseListener() {
        transaksiTable.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = transaksiTable.rowAtPoint(evt.getPoint());
                int col = transaksiTable.columnAtPoint(evt.getPoint());

                if (row >= 0) {
                    String idPesananStr = transaksiTable.getValueAt(row, 0).toString();
                    int idPesanan = Integer.parseInt(idPesananStr.replace("PES", ""));

                    if (col == 5) { // kolom aksi
                        String currentStatus = transaksiTable.getValueAt(row, 4).toString();
                        showStatusChangeDialog(idPesanan, currentStatus, row);
                    } else if (col == 6) { // kolom detail
                        showOrderDetail(idPesanan, row);
                    }
                }
            }
        });
    }
    
    private void showOrderDetail(int idPesanan, int row) {
        try {
            System.out.println("Menampilkan detail pesanan ID: " + idPesanan);

            // Ambil data detail transaksi dari service
            List<TransactionDetail> details = transactionService.getTransactionDetailsForRestoran(
                idPesanan, currentRestoran.getIdRestoran()
            );

            if (details.isEmpty()) {
                JOptionPane.showMessageDialog(this, 
                    "Tidak ditemukan detail untuk pesanan ini.", 
                    "Detail Pesanan", 
                    JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            // Ambil info dari tabel
            String idString = "PES" + String.format("%04d", idPesanan);
            String tanggal = transaksiTable.getValueAt(row, 1).toString();
            String customer = transaksiTable.getValueAt(row, 2).toString();
            String totalHarga = transaksiTable.getValueAt(row, 3).toString();
            String status = transaksiTable.getValueAt(row, 4).toString();

            // Buat dialog untuk menampilkan detail
            JDialog detailDialog = new JDialog(this, "Detail Pesanan " + idString, true);
            detailDialog.setLayout(new BorderLayout());
            detailDialog.setSize(500, 450);
            detailDialog.setLocationRelativeTo(this);

            // Panel header
            JPanel headerPanel = new JPanel(new BorderLayout());
            headerPanel.setBackground(new Color(241, 124, 42));
            headerPanel.setBorder(BorderFactory.createEmptyBorder(15, 20, 15, 20));

            JLabel headerLabel = new JLabel("Detail Pesanan #" + idString);
            headerLabel.setFont(new Font("Bahnschrift", Font.BOLD, 16));
            headerLabel.setForeground(Color.WHITE);
            headerPanel.add(headerLabel, BorderLayout.WEST);

            JLabel infoLabel = new JLabel("Resto: " + currentRestoran.getNamaRestoran());
            infoLabel.setFont(new Font("Bahnschrift", Font.PLAIN, 12));
            infoLabel.setForeground(Color.WHITE);
            headerPanel.add(infoLabel, BorderLayout.EAST);

            // Panel info pesanan
            JPanel infoPanel = new JPanel();
            infoPanel.setLayout(new BoxLayout(infoPanel, BoxLayout.Y_AXIS));
            infoPanel.setBackground(new Color(250, 240, 227));
            infoPanel.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(229, 75, 31)),
                BorderFactory.createEmptyBorder(15, 20, 15, 20)
            ));

            JLabel customerLabel = new JLabel("Customer: " + customer);
            customerLabel.setFont(new Font("Bahnschrift", Font.BOLD, 13));
            customerLabel.setForeground(new Color(59, 31, 11));

            JLabel tanggalLabel = new JLabel("Tanggal: " + tanggal);
            tanggalLabel.setFont(new Font("Bahnschrift", Font.PLAIN, 12));
            tanggalLabel.setForeground(new Color(100, 100, 100));

            JLabel statusLabel = new JLabel("Status: " + status);
            statusLabel.setFont(new Font("Bahnschrift", Font.BOLD, 12));
            statusLabel.setForeground(new Color(229, 75, 31));

            infoPanel.add(customerLabel);
            infoPanel.add(Box.createVerticalStrut(5));
            infoPanel.add(tanggalLabel);
            infoPanel.add(Box.createVerticalStrut(5));
            infoPanel.add(statusLabel);

            // Panel detail menu
            JPanel menuPanel = new JPanel();
            menuPanel.setLayout(new BoxLayout(menuPanel, BoxLayout.Y_AXIS));
            menuPanel.setBackground(Color.WHITE);
            menuPanel.setBorder(BorderFactory.createEmptyBorder(15, 20, 15, 20));

            int totalItems = 0;
            int totalPrice = 0;

            for (TransactionDetail detail : details) {
                JPanel itemPanel = new JPanel(new BorderLayout());
                itemPanel.setBorder(BorderFactory.createCompoundBorder(
                    BorderFactory.createLineBorder(new Color(220, 220, 220)),
                    BorderFactory.createEmptyBorder(10, 12, 10, 12)
                ));
                itemPanel.setBackground(Color.WHITE);

                JLabel menuLabel = new JLabel(detail.getNamaMenu());
                menuLabel.setFont(new Font("Bahnschrift", Font.BOLD, 13));
                menuLabel.setForeground(new Color(59, 31, 11));

                JLabel detailLabel = new JLabel("Jumlah: " + detail.getJumlah() + 
                                               " x Rp " + String.format("%,d", detail.getHargaSatuan()) + 
                                               " = Rp " + String.format("%,d", detail.getSubtotal()));
                detailLabel.setFont(new Font("Bahnschrift", Font.PLAIN, 12));
                detailLabel.setForeground(new Color(100, 100, 100));

                JPanel leftPanel = new JPanel(new BorderLayout());
                leftPanel.setBackground(Color.WHITE);
                leftPanel.add(menuLabel, BorderLayout.NORTH);
                leftPanel.add(Box.createVerticalStrut(3));
                leftPanel.add(detailLabel, BorderLayout.SOUTH);

                itemPanel.add(leftPanel, BorderLayout.CENTER);
                menuPanel.add(itemPanel);
                menuPanel.add(Box.createVerticalStrut(8));

                totalItems += detail.getJumlah();
                totalPrice += detail.getSubtotal();
            }

            // Panel total
            JPanel totalPanel = new JPanel(new BorderLayout());
            totalPanel.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createMatteBorder(2, 0, 0, 0, new Color(229, 75, 31)),
                BorderFactory.createEmptyBorder(15, 20, 15, 20)
            ));
            totalPanel.setBackground(new Color(250, 240, 227));

            JLabel totalItemsLabel = new JLabel("Total Items: " + totalItems);
            totalItemsLabel.setFont(new Font("Bahnschrift", Font.PLAIN, 12));
            totalItemsLabel.setForeground(new Color(59, 31, 11));

            JLabel totalPriceLabel = new JLabel("Total: Rp " + String.format("%,d", totalPrice));
            totalPriceLabel.setFont(new Font("Bahnschrift", Font.BOLD, 14));
            totalPriceLabel.setForeground(new Color(59, 31, 11));

            totalPanel.add(totalItemsLabel, BorderLayout.WEST);
            totalPanel.add(totalPriceLabel, BorderLayout.EAST);

            // Scroll pane untuk menu
            JScrollPane scrollPane = new JScrollPane(menuPanel);
            scrollPane.setBorder(BorderFactory.createEmptyBorder());
            scrollPane.getViewport().setBackground(Color.WHITE);

            // Tambahkan semua komponen ke dialog
            detailDialog.add(headerPanel, BorderLayout.NORTH);
            detailDialog.add(infoPanel, BorderLayout.CENTER);
            detailDialog.add(scrollPane, BorderLayout.CENTER);
            detailDialog.add(totalPanel, BorderLayout.SOUTH);

            detailDialog.setVisible(true);

        } catch (Exception e) {
            System.out.println("Error menampilkan detail pesanan: " + e.getMessage());
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, 
                "Error menampilkan detail: " + e.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }

    private void showStatusChangeDialog(int idPesanan, String currentStatus, int row) {
        // buat dialog custom dengan tombol-tombol status
        JDialog dialog = new JDialog(this, "Ubah Status Pesanan", true);
        dialog.setLayout(new BorderLayout());
        dialog.setSize(400, 200);
        dialog.setLocationRelativeTo(this);
        dialog.getContentPane().setBackground(new Color(250, 240, 227));
        
        // panel judul
        JLabel titleLabel = new JLabel("Ubah Status Pesanan: " + "PES" + String.format("%04d", idPesanan));
        titleLabel.setFont(new Font("Bahnschrift", Font.BOLD, 16));
        titleLabel.setForeground(new Color(59, 31, 11));
        titleLabel.setHorizontalAlignment(SwingConstants.CENTER);
        titleLabel.setBorder(new EmptyBorder(15, 15, 10, 15));
        
        // panel tombol
        JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 15, 15));
        buttonPanel.setBackground(new Color(250, 240, 227));
        buttonPanel.setBorder(new EmptyBorder(10, 15, 15, 15));
        
        // tombol-tombol status
        JButton btnMasak = createDialogButton("Sedang Dimasak", new Color(255, 193, 7));
        JButton btnAntar = createDialogButton("Sedang Diantar", new Color(33, 150, 243));
        JButton btnSampai = createDialogButton("Sudah Sampai", new Color(76, 175, 80));
        
        // atur enabled/disabled berdasarkan status saat ini
        switch (currentStatus.toUpperCase()) {
            case "PENDING":
            case "SEDANG DIBUAT":
                // Semua tombol enabled
                break;
            case "SEDANG DIANTAR":
                btnMasak.setEnabled(false);
                break;
            case "SUDAH SAMPAI":
                btnMasak.setEnabled(false);
                btnAntar.setEnabled(false);
                btnSampai.setEnabled(false);
                break;
        }
        
        // tambah action listener
        btnMasak.addActionListener(e -> {
            updateStatusAndClose(idPesanan, "SEDANG DIBUAT", dialog);
        });
        
        btnAntar.addActionListener(e -> {
            updateStatusAndClose(idPesanan, "SEDANG DIANTAR", dialog);
        });
        
        btnSampai.addActionListener(e -> {
            updateStatusAndClose(idPesanan, "SUDAH SAMPAI", dialog);
        });
        
        buttonPanel.add(btnMasak);
        buttonPanel.add(btnAntar);
        buttonPanel.add(btnSampai);
        
        dialog.add(titleLabel, BorderLayout.NORTH);
        dialog.add(buttonPanel, BorderLayout.CENTER);
        
        dialog.setVisible(true);
    }

    private JButton createDialogButton(String text, Color color) {
        JButton button = new JButton(text);
        button.setFont(new Font("Bahnschrift", Font.BOLD, 12));
        button.setBackground(color);
        button.setForeground(Color.WHITE);
        button.setFocusPainted(false);
        button.setBorder(BorderFactory.createEmptyBorder(10, 20, 10, 20));
        button.setPreferredSize(new Dimension(120, 40));
        
        // hover effect
        button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button.setBackground(color.darker());
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button.setBackground(color);
            }
        });
        
        return button;
    }

    private void updateStatusAndClose(int idPesanan, String newStatus, JDialog dialog) {
        updateStatusPesanan(idPesanan, newStatus);
        dialog.dispose();
    }
    
    private void openTambahMenuFrame() {
        TambahMenuFrame dialog = new TambahMenuFrame(this, currentRestoran);
        dialog.setVisible(true);
    }
    
    private void openEditMenuFrame(int idMenu, String namaMenu, int harga) {
        EditMenuFrame edit = new EditMenuFrame(this, currentRestoran, idMenu, namaMenu, harga);
        edit.setVisible(true);
    }
    
    private void deleteMenu(int idMenu) {
        try {
            // konfirmasi penghapusan
            int confirm = JOptionPane.showConfirmDialog(this, 
                "Apakah Anda yakin ingin menghapus menu ini?\n" +
                "(Akan menghapus semua data terkait di keranjang dan detail pesanan)", 
                "Konfirmasi Hapus", 
                JOptionPane.YES_NO_OPTION);

            if (confirm != JOptionPane.YES_OPTION) {
                return;
            }

            // 1. hapus dari detail_pesanan terlebih dahulu (karena foreign key ke menu)
            String sqlDetail = "DELETE FROM detail_pesanan WHERE id_menu = " + idMenu;
            auth.getKonektor().query(sqlDetail);
            System.out.println("Deleted from detail_pesanan for menu ID: " + idMenu);

            // 2. hapus dari keranjang
            String sqlKeranjang = "DELETE FROM keranjang WHERE id_menu = " + idMenu;
            auth.getKonektor().query(sqlKeranjang);
            System.out.println("Deleted from keranjang for menu ID: " + idMenu);

            // 3. baru hapus dari menu
            String sqlMenu = "DELETE FROM menu WHERE id_menu = " + idMenu;
            auth.getKonektor().query(sqlMenu);
            System.out.println("Deleted from menu for menu ID: " + idMenu);

            JOptionPane.showMessageDialog(this, "Menu berhasil dihapus!");
            loadMenuFromDatabase();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                "Gagal menghapus menu: " + e.getMessage() + 
                "\n\nPastikan tidak ada pesanan aktif yang menggunakan menu ini.",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // dipanggil oleh TambahMenuFrame setelah insert
    public void refreshAfterAddMenu() {
        loadMenuFromDatabase();
    }
    
    private void loadMenuFromDatabase() {
        if (menuContainer == null) return;
        menuContainer.removeAll();

        try {
            String sql = "SELECT * FROM menu WHERE id_restoran = " + currentRestoran.getIdRestoran() + " ORDER BY nama_menu";
            ResultSet rs = auth.getKonektor().getData(sql);

            boolean any = false;
            while (rs != null && rs.next()) {
                any = true;
                int idMenu = rs.getInt("id_menu");
                String nama = rs.getString("nama_menu");
                int harga = rs.getInt("harga");

                JPanel card = createMenuCard(idMenu, nama, harga);
                menuContainer.add(card);
                menuContainer.add(Box.createVerticalStrut(10));
            }

            if (!any) {
                JPanel messagePanel = new JPanel(new BorderLayout());
                messagePanel.setOpaque(false);
                JLabel l = new JLabel("Tidak ada menu. Klik 'Tambah Menu +' untuk menambahkan.");
                l.setFont(new Font("Bahnschrift", Font.PLAIN, 14));
                l.setForeground(new Color(120, 120, 120));
                l.setHorizontalAlignment(SwingConstants.CENTER);
                messagePanel.add(l, BorderLayout.CENTER);
                menuContainer.add(messagePanel);
            }

        } catch (Exception e) {
            System.out.println("Load menu error: " + e.getMessage());
            e.printStackTrace();
            JPanel messagePanel = new JPanel(new BorderLayout());
            messagePanel.setOpaque(false);
            JLabel l = new JLabel("Error: Tidak dapat memuat menu dari database");
            l.setFont(new Font("Bahnschrift", Font.BOLD, 14));
            l.setForeground(Color.RED);
            l.setHorizontalAlignment(SwingConstants.CENTER);
            messagePanel.add(l, BorderLayout.CENTER);
            menuContainer.add(messagePanel);
        }

        menuContainer.revalidate();
        menuContainer.repaint();
    }

    private void loadTransaksiFromDatabase() {
        if (transaksiTableModel == null) return;
        transaksiTableModel.setRowCount(0);

        try {
            String sql = "SELECT p.id_pesanan, p.tanggal_pesan, p.status_pesanan, " +
                        "u.nama as nama_customer, " +
                        "SUM(d.jumlah * d.harga_satuan) as total_harga " +
                        "FROM pesanan p " +
                        "JOIN user u ON p.id_user = u.id_user " +
                        "LEFT JOIN detail_pesanan d ON p.id_pesanan = d.id_pesanan " +
                        "WHERE p.id_restoran = " + currentRestoran.getIdRestoran() + " " +
                        "GROUP BY p.id_pesanan, p.tanggal_pesan, p.status_pesanan, u.nama " +
                        "ORDER BY p.tanggal_pesan DESC";

            ResultSet rs = auth.getKonektor().getData(sql);

            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm");

            while (rs != null && rs.next()) {
                int idPesanan = rs.getInt("id_pesanan");
                String tanggal = dateFormat.format(rs.getTimestamp("tanggal_pesan"));
                String customer = rs.getString("nama_customer");
                int total = rs.getInt("total_harga");
                String status = rs.getString("status_pesanan");

                // tampilkan teks "Klik untuk ubah status" di kolom aksi dan "Lihat Detail" di kolom detail
                transaksiTableModel.addRow(new Object[]{
                    "PES" + String.format("%04d", idPesanan),
                    tanggal,
                    customer,
                    String.format("Rp %,d", total),
                    status,
                    "✏️ Ubah Status",
                    "📋 Lihat Detail"  // TAMBAHKAN INI
                });
            }

            // set column widths
            transaksiTable.getColumnModel().getColumn(0).setPreferredWidth(80);  // ID
            transaksiTable.getColumnModel().getColumn(1).setPreferredWidth(120); // Tanggal
            transaksiTable.getColumnModel().getColumn(2).setPreferredWidth(120); // Customer
            transaksiTable.getColumnModel().getColumn(3).setPreferredWidth(100); // Total
            transaksiTable.getColumnModel().getColumn(4).setPreferredWidth(100); // Status
            transaksiTable.getColumnModel().getColumn(5).setPreferredWidth(120); // Aksi
            transaksiTable.getColumnModel().getColumn(6).setPreferredWidth(120); // Detail

        } catch (Exception e) {
            System.out.println("Load transaksi error: " + e.getMessage());
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                "Error: Tidak dapat memuat data transaksi",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void updateStatusPesanan(int idPesanan, String statusBaru) {
        try {
            String sql = "UPDATE pesanan SET status_pesanan = '" + statusBaru + "' WHERE id_pesanan = " + idPesanan;
            auth.getKonektor().query(sql);

            JOptionPane.showMessageDialog(this, 
                "Status pesanan berhasil diupdate menjadi: " + statusBaru, 
                "Sukses", 
                JOptionPane.INFORMATION_MESSAGE);

            // refresh data transaksi
            loadTransaksiFromDatabase();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                "Gagal mengupdate status pesanan: " + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private JPanel createMenuCard(int idMenu, String namaMenu, int harga) {
        JPanel card = new JPanel(new BorderLayout()) {
            @Override
            protected void paintComponent(Graphics g) {
                Graphics2D g2 = (Graphics2D) g;
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(Color.WHITE);
                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 20, 20);
                g2.setColor(new Color(229, 75, 31));
                g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 20, 20);
            }
        };
        card.setOpaque(false);
        card.setBorder(new EmptyBorder(12, 16, 12, 16));
        card.setMaximumSize(new Dimension(700, 90));

        JLabel lblNama = new JLabel(namaMenu);
        lblNama.setFont(new Font("Bahnschrift", Font.BOLD, 16));
        lblNama.setForeground(new Color(59, 31, 11));

        JLabel lblHarga = new JLabel("Rp " + harga);
        lblHarga.setFont(new Font("Bahnschrift", Font.PLAIN, 14));
        lblHarga.setForeground(new Color(59, 31, 11));

        JPanel left = new JPanel();
        left.setOpaque(false);
        left.setLayout(new BoxLayout(left, BoxLayout.Y_AXIS));
        left.add(lblNama);
        left.add(lblHarga);

        JPanel right = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        right.setOpaque(false);

        // tombol edit
        JButton editBtn = createSmallButton("Edit", new Color(241, 124, 42));
        editBtn.addActionListener(e -> openEditMenuFrame(idMenu, namaMenu, harga));

        // tombol delete
        JButton deleteBtn = createSmallButton("Hapus", new Color(200, 0, 0));
        deleteBtn.addActionListener(e -> deleteMenu(idMenu));

        right.add(editBtn);
        right.add(deleteBtn);

        card.add(left, BorderLayout.WEST);
        card.add(right, BorderLayout.EAST);

        return card;
    }
    
    private JButton createSmallButton(String text, Color color) {
        JButton btn = new JButton(text);
        btn.setForeground(Color.WHITE);
        btn.setBackground(color);
        btn.setFocusPainted(false);
        btn.setBorder(new EmptyBorder(6, 12, 6, 12));
        return btn;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        SwingUtilities.invokeLater(() -> {
            JOptionPane.showMessageDialog(null, "Jalankan DashboardRestoranFrame dari Login setelah loginRestoran sukses.", "Info", JOptionPane.INFORMATION_MESSAGE);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}