/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JatoStyle.gui;

import JatoStyle.models.User;
import JatoStyle.models.Restoran;
import JatoStyle.models.Review;
import JatoStyle.services.ReviewService;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.*;
import java.awt.event.*;
import java.text.SimpleDateFormat;
import java.util.List;

public class LihatReviewFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LihatReviewFrame.class.getName());
    private User currentUser;
    private Restoran currentRestoran;
    private ReviewService reviewService;
    private JPanel reviewContainer;
    private Review userReview;

    /**
     * Creates new form LihatReviewFrame
     */
    public LihatReviewFrame(User user, Restoran restoran, ReviewService reviewService) {
        this.currentUser = user;
        this.currentRestoran = restoran;
        this.reviewService = reviewService;
        initComponents();
        setLocationRelativeTo(null);
        setupUI();
        loadReviews();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoutButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        haloNamaOutput = new javax.swing.JTextField();
        reviewOutput = new javax.swing.JScrollPane();
        backButton = new javax.swing.JButton();
        profilButton = new javax.swing.JButton();
        addReviewButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logoutButton.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JatoStyle/gui/dashboardlogo.png"))); // NOI18N

        haloNamaOutput.setEditable(false);
        haloNamaOutput.setBackground(new java.awt.Color(250, 240, 227));
        haloNamaOutput.setFont(new java.awt.Font("Bahnschrift", 1, 20)); // NOI18N
        haloNamaOutput.setForeground(new java.awt.Color(250, 240, 227));
        haloNamaOutput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        haloNamaOutput.setBorder(null);
        haloNamaOutput.setDisabledTextColor(new java.awt.Color(59, 31, 11));
        haloNamaOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                haloNamaOutputActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        profilButton.setText("👤");
        profilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilButtonActionPerformed(evt);
            }
        });

        addReviewButton.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        addReviewButton.setText("+ Add Your Review");
        addReviewButton.setMaximumSize(new java.awt.Dimension(150, 28));
        addReviewButton.setMinimumSize(new java.awt.Dimension(150, 28));
        addReviewButton.setPreferredSize(new java.awt.Dimension(150, 28));
        addReviewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addReviewButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addReviewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(haloNamaOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(logoutButton)
                        .addGap(18, 18, 18)
                        .addComponent(profilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(reviewOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backButton)
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(haloNamaOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(profilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addComponent(addReviewButton, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reviewOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backButton)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fixButtonSize() {
        // Atur ukuran tetap untuk tombol addReviewButton
        addReviewButton.setPreferredSize(new Dimension(169, 30));
        addReviewButton.setMaximumSize(new Dimension(169, 30));
        addReviewButton.setMinimumSize(new Dimension(169, 30));

        // Atur margin/inset yang kecil
        Insets buttonInsets = new Insets(4, 12, 4, 12);
        addReviewButton.setMargin(buttonInsets);

        // Refresh tombol
        addReviewButton.revalidate();
        addReviewButton.repaint();
    }
    
    private void setupUI() {
        // Set null layout untuk manual positioning
        getContentPane().setLayout(null);

        applyTemplateStyles();
        initDynamicUI();

        // Set window size - DIPERKECIL
        setSize(900, 600);
        setLocationRelativeTo(null);

        // ========== MANUAL POSITIONING SEMUA KOMPONEN ==========

        // Logo (jLabel1)
        jLabel1.setBounds(29, 28, jLabel1.getPreferredSize().width, jLabel1.getPreferredSize().height);

        // Title text (haloNamaOutput) - LEBIH KE TENGAH & HILANGKAN CARET
        haloNamaOutput.setText("Review untuk " + currentRestoran.getNamaRestoran());
        haloNamaOutput.setHorizontalAlignment(SwingConstants.CENTER);
        haloNamaOutput.setFocusable(false); // HILANGKAN CARET tanpa setCaret(null)
        haloNamaOutput.setHighlighter(null); // Hilangkan highlighter
        haloNamaOutput.setBounds(
            150, 
            50, 
            520, 
            30
        );

        // Logout button - DIGESER KE KIRI
        logoutButton.setBounds(680, 45, 75, 35);

        // Profile button - DIGESER KE KIRI
        profilButton.setBounds(773, 45, 50, 50);

        // ADD REVIEW BUTTON - UKURAN KECIL
        addReviewButton.setText("+ Add Review");
        addReviewButton.setFont(new Font("Bahnschrift", Font.PLAIN, 10));
        addReviewButton.setBounds(29, 110, 120, 26);

        // Review output scroll pane - DIPERBESAR TINGGINYA
        reviewOutput.setBounds(29, 148, 842, 360);

        // Back button - POSISI LEBIH MUDAH DIJANGKAU
        backButton.setBounds(760, 520, 75, 30);

        // ====================================================

        SwingUtilities.invokeLater(() -> {
            reviewOutput.getViewport().setViewPosition(new Point(0, 0));
        });
    }

    private void applyTemplateStyles() {
        getContentPane().setBackground(new Color(250, 240, 227));
        setTitle("Review - " + currentRestoran.getNamaRestoran());

        haloNamaOutput.setBackground(new Color(250, 240, 227));
        haloNamaOutput.setForeground(new Color(59, 31, 11));
        haloNamaOutput.setBorder(null);
        haloNamaOutput.setFont(new Font("Bahnschrift", Font.BOLD, 18));

        // UKURAN KECIL UNTUK ADD/EDIT BUTTON
        Dimension fixedSize = new Dimension(120, 26);
        Insets tinyInsets = new Insets(2, 5, 2, 5);

        addReviewButton.setPreferredSize(fixedSize);
        addReviewButton.setMinimumSize(fixedSize);
        addReviewButton.setMaximumSize(fixedSize);
        addReviewButton.setMargin(tinyInsets);
        addReviewButton.setFont(new Font("Bahnschrift", Font.PLAIN, 10));
        addReviewButton.setBackground(new Color(241, 124, 42));
        addReviewButton.setForeground(Color.WHITE);
        addReviewButton.setFocusPainted(false);
        addReviewButton.setBorder(BorderFactory.createEmptyBorder(2, 5, 2, 5));

        backButton.setBackground(new Color(229, 75, 31));
        backButton.setForeground(Color.WHITE);
        backButton.setFocusPainted(false);
        backButton.setFont(new Font("Bahnschrift", Font.PLAIN, 13));

        profilButton.setBackground(new Color(241, 124, 42));
        profilButton.setForeground(Color.WHITE);
        profilButton.setFocusPainted(false);
        profilButton.setFont(new Font("Bahnschrift", Font.PLAIN, 14));

        logoutButton.setBackground(new Color(229, 75, 31));
        logoutButton.setForeground(Color.WHITE);
        logoutButton.setFocusPainted(false);
        logoutButton.setFont(new Font("Bahnschrift", Font.PLAIN, 11));
    }

    private void initDynamicUI() {
        // Review container dengan kontrol tinggi maksimum
        reviewContainer = new JPanel() {
            @Override
            public Dimension getPreferredSize() {
                Dimension dim = super.getPreferredSize();
                // Batasi tinggi maksimum container
                dim.height = Math.min(dim.height, 500);
                return dim;
            }
        };
        reviewContainer.setBackground(new Color(250, 240, 227));
        reviewContainer.setLayout(new BoxLayout(reviewContainer, BoxLayout.Y_AXIS));
        reviewContainer.setBorder(new EmptyBorder(5, 15, 5, 15)); // Padding minimal

        // Gunakan wrapper panel untuk push konten ke atas
        JPanel wrapperPanel = new JPanel(new BorderLayout());
        wrapperPanel.setBackground(new Color(250, 240, 227));
        wrapperPanel.add(reviewContainer, BorderLayout.NORTH); // NORTH agar content naik

        // Tambahkan glue di bawah untuk push content ke atas
        wrapperPanel.add(Box.createVerticalGlue(), BorderLayout.SOUTH);

        reviewOutput.setViewportView(wrapperPanel);
        reviewOutput.setBorder(BorderFactory.createLineBorder(new Color(229, 75, 31), 1));
        reviewOutput.getViewport().setBackground(new Color(250, 240, 227));
        reviewOutput.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);

        // Atur scroll bar
        JScrollBar verticalBar = reviewOutput.getVerticalScrollBar();
        verticalBar.setUnitIncrement(16);
        verticalBar.setBlockIncrement(50);
    }

    private void loadReviews() {
        if (reviewContainer == null) return;
        reviewContainer.removeAll();

        try {
            userReview = reviewService.getUserReviewForRestoran(
                currentUser.getIdUser(), 
                currentRestoran.getIdRestoran()
            );

            if (userReview != null) {
                addReviewButton.setText("Edit Review");
            } else {
                addReviewButton.setText("+ Add Review");
            }

            // TETAP PAKSA UKURAN 120x26
            addReviewButton.setBounds(29, 120, 120, 26);
            addReviewButton.setFont(new Font("Bahnschrift", Font.PLAIN, 10));

            boolean hasPurchased = reviewService.hasUserPurchasedFromRestoran(
                currentUser.getIdUser(),
                currentRestoran.getIdRestoran()
            );

            if (!hasPurchased) {
                addReviewButton.setEnabled(false);
                addReviewButton.setToolTipText("You need to have completed a purchase to review this restaurant");
                addReviewButton.setBackground(Color.GRAY);
            } else {
                addReviewButton.setEnabled(true);
                addReviewButton.setBackground(new Color(241, 124, 42));
            }

            List<Review> reviews = reviewService.getAllReviewsForRestoran(currentRestoran.getIdRestoran());
            double avgRating = reviewService.getAverageRating(currentRestoran.getIdRestoran());
            int totalReviews = reviewService.getTotalReviews(currentRestoran.getIdRestoran());

            JPanel summaryPanel = createCompactSummaryPanel(avgRating, totalReviews);
            reviewContainer.add(summaryPanel);
            reviewContainer.add(Box.createVerticalStrut(5));

            if (reviews.isEmpty()) {
                JPanel messagePanel = new JPanel(new BorderLayout());
                messagePanel.setOpaque(false);
                messagePanel.setMaximumSize(new Dimension(Integer.MAX_VALUE, 40));
                JLabel label = new JLabel("Belum ada review untuk restoran ini.");
                label.setFont(new Font("Bahnschrift", Font.PLAIN, 12));
                label.setForeground(new Color(120, 120, 120));
                label.setHorizontalAlignment(SwingConstants.CENTER);
                messagePanel.add(label, BorderLayout.CENTER);
                reviewContainer.add(messagePanel);
            } else {
                for (int i = 0; i < reviews.size(); i++) {
                    Review review = reviews.get(i);
                    JPanel reviewCard = createCompactReviewCard(review);
                    reviewContainer.add(reviewCard);

                    if (i < reviews.size() - 1) {
                        reviewContainer.add(Box.createVerticalStrut(5));
                    }
                }
            }

        } catch (Exception e) {
            System.out.println("Error loading reviews: " + e.getMessage());
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                "Error loading reviews: " + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        }

        reviewContainer.revalidate();
        reviewContainer.repaint();

        SwingUtilities.invokeLater(() -> {
            reviewOutput.getViewport().setViewPosition(new Point(0, 0));
        });
    }

    private JPanel createCompactSummaryPanel(double avgRating, int totalReviews) {
        JPanel panel = new JPanel(new BorderLayout());
        panel.setOpaque(false);
        panel.setBorder(new EmptyBorder(5, 5, 5, 5)); // Padding minimal
        panel.setMaximumSize(new Dimension(Integer.MAX_VALUE, 35)); // Batasi tinggi

        JLabel titleLabel = new JLabel("Review untuk " + currentRestoran.getNamaRestoran());
        titleLabel.setFont(new Font("Bahnschrift", Font.BOLD, 14)); // Font lebih kecil
        titleLabel.setForeground(new Color(59, 31, 11));

        JLabel ratingLabel = new JLabel(String.format("Rata-rata: %.1f/5 (%d)", avgRating, totalReviews));
        ratingLabel.setFont(new Font("Bahnschrift", Font.PLAIN, 11)); // Font kecil
        ratingLabel.setForeground(new Color(59, 31, 11));

        panel.add(titleLabel, BorderLayout.WEST);
        panel.add(ratingLabel, BorderLayout.EAST);

        return panel;
    }

    private JPanel createCompactReviewCard(Review review) {
        // Panel card dengan tinggi terbatas
        JPanel card = new JPanel(new BorderLayout()) {
            @Override
            public Dimension getPreferredSize() {
                // Batasi tinggi card
                return new Dimension(super.getPreferredSize().width, 100);
            }

            @Override
            public Dimension getMaximumSize() {
                return new Dimension(Integer.MAX_VALUE, 100);
            }

            @Override
            protected void paintComponent(Graphics g) {
                Graphics2D g2 = (Graphics2D) g;
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(Color.WHITE);
                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 8, 8); // Radius kecil
                g2.setColor(new Color(229, 75, 31, 100)); // Warna transparan
                g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 8, 8);
            }
        };

        card.setOpaque(false);
        card.setBorder(new EmptyBorder(8, 12, 8, 12)); // Padding minimal

        // Header panel - sangat compact
        JPanel headerPanel = new JPanel(new BorderLayout());
        headerPanel.setOpaque(false);
        headerPanel.setMaximumSize(new Dimension(Integer.MAX_VALUE, 25)); // Batasi tinggi

        // Nama user
        JLabel userLabel = new JLabel(review.getNamaUser());
        userLabel.setFont(new Font("Bahnschrift", Font.BOLD, 11)); // Font kecil
        userLabel.setForeground(new Color(59, 31, 11));

        // Rating stars - PERBAIKI DENGAN FONT YANG SUPPORT UNICODE
        JPanel ratingPanel = new JPanel(new FlowLayout(FlowLayout.LEFT, 1, 0));
        ratingPanel.setOpaque(false);
        ratingPanel.setMaximumSize(new Dimension(120, 20));

        // Coba font yang berbeda untuk mendukung simbol bintang
        Font starFont;
        String[] fontNames = {"Segoe UI Symbol", "Arial Unicode MS", "DejaVu Sans", "SansSerif"};
        Font availableFont = null;

        // Cari font yang tersedia di sistem
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        String[] availableFonts = ge.getAvailableFontFamilyNames();

        for (String fontName : fontNames) {
            for (String available : availableFonts) {
                if (available.equalsIgnoreCase(fontName)) {
                    availableFont = new Font(fontName, Font.PLAIN, 12);
                    break;
                }
            }
            if (availableFont != null) break;
        }

        // Jika tidak ada font khusus, gunakan default
        if (availableFont == null) {
            availableFont = new Font("SansSerif", Font.PLAIN, 12);
        }

        for (int i = 0; i < 5; i++) {
            // Gunakan karakter bintang Unicode
            String starChar = (i < review.getRating()) ? "★" : "☆";
            JLabel star = new JLabel(starChar);
            star.setFont(availableFont);
            star.setForeground(i < review.getRating() ? new Color(255, 193, 7) : new Color(200, 200, 200));
            ratingPanel.add(star);
        }

        // Alternatif: Jika masih tidak muncul, gunakan HTML entities
        // String filledStar = "&#9733;"; // ★
        // String emptyStar = "&#9734;"; // ☆

        JLabel ratingText = new JLabel(" " + review.getRating() + "/5");
        ratingText.setFont(new Font("Bahnschrift", Font.PLAIN, 11));
        ratingText.setForeground(new Color(100, 100, 100));
        ratingPanel.add(ratingText);

        headerPanel.add(userLabel, BorderLayout.WEST);
        headerPanel.add(ratingPanel, BorderLayout.EAST);

        // Komentar area - compact
        JTextArea komentarArea = new JTextArea(review.getKomentar()) {
            @Override
            public Dimension getPreferredSize() {
                // Batasi tinggi area komentar
                return new Dimension(super.getPreferredSize().width, 45);
            }
        };
        komentarArea.setEditable(false);
        komentarArea.setLineWrap(true);
        komentarArea.setWrapStyleWord(true);
        komentarArea.setFont(new Font("Bahnschrift", Font.PLAIN, 10)); // Font sangat kecil
        komentarArea.setForeground(new Color(59, 31, 11));
        komentarArea.setBackground(Color.WHITE);
        komentarArea.setBorder(new EmptyBorder(3, 2, 3, 2)); // Padding minimal
        komentarArea.setRows(2); // Maksimal 2 baris
        komentarArea.setLineWrap(true);
        komentarArea.setWrapStyleWord(true);

        // Footer panel - sangat compact
        JPanel footerPanel = new JPanel(new BorderLayout());
        footerPanel.setOpaque(false);
        footerPanel.setMaximumSize(new Dimension(Integer.MAX_VALUE, 15)); // Batasi tinggi

        // Format tanggal
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yy HH:mm");
        String dateText = dateFormat.format(review.getTanggalReview());

        if (review.getLastEdited() != null) {
            dateText += " (edit)";
        }

        JLabel dateLabel = new JLabel(dateText);
        dateLabel.setFont(new Font("Bahnschrift", Font.PLAIN, 8)); // Font sangat kecil
        dateLabel.setForeground(new Color(150, 150, 150));

        // Label "Your Review" jika milik user
        if (review.getIdUser() == currentUser.getIdUser()) {
            JLabel yourReviewLabel = new JLabel("Review Anda");
            yourReviewLabel.setFont(new Font("Bahnschrift", Font.BOLD, 8));
            yourReviewLabel.setForeground(new Color(33, 150, 243));
            footerPanel.add(yourReviewLabel, BorderLayout.WEST);
        }

        footerPanel.add(dateLabel, BorderLayout.EAST);

        // Tambahkan semua ke card
        card.add(headerPanel, BorderLayout.NORTH);
        card.add(komentarArea, BorderLayout.CENTER);
        card.add(footerPanel, BorderLayout.SOUTH);

        return card;
    }
    
    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        int confirm = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Apakah Anda yakin ingin logout?",
            "Konfirmasi Logout",
            javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            // tutup dashboard
            this.dispose();

            // buka lagi login frame
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new JatoStyle.gui.LoginFrame().setVisible(true);
                }
            });

            System.out.println("User logged out successfully");
        }
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void haloNamaOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_haloNamaOutputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_haloNamaOutputActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // Kembali ke RestoranFrame
        RestoranFrame restoFrame = new RestoranFrame(currentUser, currentRestoran);
        restoFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void profilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilButtonActionPerformed
        ProfileFrame pf = new ProfileFrame(currentUser, this); // kirim data user + frame dashboard
        pf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_profilButtonActionPerformed

    private void addReviewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addReviewButtonActionPerformed
        // Cek apakah user sudah pernah beli di resto ini
        boolean hasPurchased = reviewService.hasUserPurchasedFromRestoran(
            currentUser.getIdUser(),
            currentRestoran.getIdRestoran()
        );

        if (!hasPurchased) {
            JOptionPane.showMessageDialog(this,
                "You need to complete a purchase from this restaurant before you can leave a review.\n" +
                "Only users with completed orders (status: SUDAH SAMPAI) can review.",
                "Cannot Review",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Buka dialog add/edit review
        AddReviewDialog dialog = new AddReviewDialog(
            this,
            currentUser,
            currentRestoran,
            reviewService,
            userReview
        );

        dialog.setVisible(true);

        // Refresh setelah dialog ditutup
        if (dialog.isReviewSaved()) {
            loadReviews();
        }
    }//GEN-LAST:event_addReviewButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addReviewButton;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField haloNamaOutput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton profilButton;
    private javax.swing.JScrollPane reviewOutput;
    // End of variables declaration//GEN-END:variables
}
