/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JatoStyle.gui;

import JatoStyle.services.AuthService;
import JatoStyle.models.User;
import javax.swing.JOptionPane;
import java.awt.Color;
import javax.swing.BorderFactory;
import java.awt.Cursor;
import JatoStyle.services.PasswordHasher; 

public class RegisterFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegisterFrame.class.getName());

    public RegisterFrame() {
        initComponents();
        
        applyCustomStyles();
        setupLoginTextClickListener(); 
    }
    
    private boolean isValidNoTelp(String noTelp) {
        if (noTelp == null || noTelp.trim().isEmpty()) {
            return false;
        }
        // hanya angka, min 10 digit, maks 13 digit
        return noTelp.matches("\\d{10,13}");
    }

    private boolean isValidPassword(String password) {
        if (password == null || password.trim().isEmpty()) {
            return false;
        }
        // minimal 8 karakter
        return password.length() >= 8;
    }
    
    private void setupLoginTextClickListener() {
        loginText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginTextMouseClicked(evt);
            }
        });
    }

    private void applyCustomStyles() {
        // background #FAF0E3 (sama dengan LoginFrame)
        getContentPane().setBackground(new Color(250, 240, 227));

        // panel register - ubah menjadi warna (0, 51, 79) seperti LoginFrame
        jPanel1.setBackground(new Color(0, 51, 79));
        jPanel1.setBorder(BorderFactory.createLineBorder(new Color(0, 51, 79), 1));

        // title LOGIN - ubah menjadi warna (206, 220, 239) seperti LoginFrame
        jLabel1.setForeground(new Color(206, 220, 239));

        // labels - ubah menjadi warna (206, 220, 239) seperti LoginFrame
        jLabel2.setForeground(new Color(206, 220, 239));
        jLabel3.setForeground(new Color(206, 220, 239));
        jLabel4.setForeground(new Color(206, 220, 239));
        jLabel6.setForeground(new Color(206, 220, 239));
        jLabel7.setForeground(new Color(206, 220, 239));

        // input fields dengan border berwarna (149, 189, 226) seperti LoginFrame
        namaInput.setBackground(Color.WHITE);
        namaInput.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(new Color(149, 189, 226), 2),
            BorderFactory.createEmptyBorder(8, 10, 8, 10)
        ));

        emailInput.setBackground(Color.WHITE);
        emailInput.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(new Color(149, 189, 226), 2),
            BorderFactory.createEmptyBorder(8, 10, 8, 10)
        ));

        noTelpInput.setBackground(Color.WHITE);
        noTelpInput.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(new Color(149, 189, 226), 2),
            BorderFactory.createEmptyBorder(8, 10, 8, 10)
        ));

        passwordInput.setBackground(Color.WHITE);
        passwordInput.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(new Color(149, 189, 226), 2),
            BorderFactory.createEmptyBorder(8, 10, 8, 10)
        ));

        confirmPasswordInput.setBackground(Color.WHITE);
        confirmPasswordInput.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(new Color(149, 189, 226), 2),
            BorderFactory.createEmptyBorder(8, 10, 8, 10)
        ));

        // register button dengan warna (149, 189, 226) dan teks warna gelap seperti login button
        registerButton.setBackground(new Color(149, 189, 226));
        registerButton.setForeground(new Color(59, 31, 11)); // Warna gelap agar kontras
        registerButton.setBorder(BorderFactory.createEmptyBorder(10, 0, 10, 0));
        registerButton.setFocusPainted(false);

        // login text - atur semua teks menjadi putih dengan underline untuk "Login here"
        loginText.setText("<html><font color='white'>Already have an account? <u>Login here</u></font></html>");
        loginText.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        namaInput = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        registerButton = new javax.swing.JButton();
        loginText = new javax.swing.JLabel();
        emailInput = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        noTelpInput = new javax.swing.JTextField();
        confirmPasswordInput = new javax.swing.JPasswordField();
        passwordInput = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 650));
        setSize(new java.awt.Dimension(800, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JatoStyle/gui/JatoStyle_Front_Logo.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 126, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setMaximumSize(new java.awt.Dimension(350, 400));
        jPanel1.setMinimumSize(new java.awt.Dimension(350, 400));
        jPanel1.setRequestFocusEnabled(false);

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel1.setText("Register");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setText("Nama Lengkap");

        namaInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaInputActionPerformed(evt);
            }
        });
        namaInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                namaInputKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setText("Email");

        registerButton.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        registerButton.setText("Register");
        registerButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        loginText.setText("<html>Already have an account? <a href='#'>Login here</a></html>");

        emailInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailInputActionPerformed(evt);
            }
        });
        emailInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emailInputKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setText("Nomor Telepon");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setText("Password");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setText("Confirm Password");

        noTelpInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noTelpInputActionPerformed(evt);
            }
        });
        noTelpInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                noTelpInputKeyPressed(evt);
            }
        });

        confirmPasswordInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPasswordInputActionPerformed(evt);
            }
        });
        confirmPasswordInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                confirmPasswordInputKeyPressed(evt);
            }
        });

        passwordInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordInputActionPerformed(evt);
            }
        });
        passwordInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordInputKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(namaInput, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                                .addComponent(loginText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(emailInput, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                                .addComponent(noTelpInput, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                                .addComponent(confirmPasswordInput)
                                .addComponent(passwordInput))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel1)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(namaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(emailInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(12, 12, 12)
                .addComponent(noTelpInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(confirmPasswordInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 34, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JatoStyle/gui/bg_register_fix.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 810, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namaInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaInputActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        String nama = namaInput.getText().trim();
        String email = emailInput.getText().trim();
        String noTelp = noTelpInput.getText().trim();
        String password = new String(passwordInput.getPassword());
        String confirmPassword = new String(confirmPasswordInput.getPassword());

        // object AuthService
        AuthService authService = new AuthService();

        // validasi input kosong
        if (nama.isEmpty() || email.isEmpty() || noTelp.isEmpty() || password.isEmpty() || confirmPassword.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Semua field harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // validasi format email
        if (!authService.isValidEmail(email)) {
            JOptionPane.showMessageDialog(this, 
                "Format email tidak valid!\n" +
                "• Harus mengandung @\n" +
                "• Harus mengandung domain (.com, .net, dll)\n" +
                "• Minimal 5 karakter", 
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // validasi no telp, min 10 max 13 digit
        if (!isValidNoTelp(noTelp)) {
            JOptionPane.showMessageDialog(this, 
                "Format nomor telepon tidak valid!\n" +
                "• Harus berupa angka\n" +
                "• Minimal 10 digit\n" +
                "• Maksimal 13 digit", 
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // validasi password min 8 karakter)
        if (!isValidPassword(password)) {
            JOptionPane.showMessageDialog(this, 
                "Password terlalu pendek!\n" +
                "• Minimal 8 karakter", 
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // validasi confirm password
        if (!password.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(this, 
                "Password dan Confirm Password tidak sama!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
        }

        // validasi email sudah terdaftar
        if (authService.isEmailExists(email, "user")) {
            JOptionPane.showMessageDialog(this, 
                "Email sudah terdaftar!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // proses register
        try {

            // buat user dengan password yang sudah dihash
            User newUser = new User(nama, email, password, noTelp);

            boolean success = authService.registerUser(newUser);

            if (success) {
                JOptionPane.showMessageDialog(this, 
                    "Registrasi berhasil! Silakan login.", "Success", JOptionPane.INFORMATION_MESSAGE);
                new LoginFrame().setVisible(true);
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, 
                    "Registrasi gagal!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, 
                "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_registerButtonActionPerformed

    private void emailInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailInputActionPerformed

    private void noTelpInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noTelpInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noTelpInputActionPerformed

    private void passwordInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordInputActionPerformed

    private void confirmPasswordInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPasswordInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmPasswordInputActionPerformed

    private void namaInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_namaInputKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            emailInput.requestFocus();
        }
    }//GEN-LAST:event_namaInputKeyPressed

    private void emailInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailInputKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            noTelpInput.requestFocus();
        }
    }//GEN-LAST:event_emailInputKeyPressed

    private void noTelpInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noTelpInputKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            passwordInput.requestFocus();
        }
    }//GEN-LAST:event_noTelpInputKeyPressed

    private void passwordInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordInputKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            confirmPasswordInput.requestFocus();
        }
    }//GEN-LAST:event_passwordInputKeyPressed

    private void confirmPasswordInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirmPasswordInputKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            registerButton.doClick();  
        }
    }//GEN-LAST:event_confirmPasswordInputKeyPressed

    private void loginTextMouseClicked(java.awt.event.MouseEvent evt) {                                       
        new LoginFrame().setVisible(true);
        this.dispose();
    }                                      

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegisterFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirmPasswordInput;
    private javax.swing.JTextField emailInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel loginText;
    private javax.swing.JTextField namaInput;
    private javax.swing.JTextField noTelpInput;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JButton registerButton;
    // End of variables declaration//GEN-END:variables
}
