/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JatoStyle.gui;

import JatoStyle.models.Toko;
import JatoStyle.models.User;
import JatoStyle.services.AuthService;
import java.awt.*;
import java.sql.ResultSet;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import javax.swing.border.Border;
import JatoStyle.services.ReviewService;
import JatoStyle.models.Review;

public class RestoranFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RestoranFrame.class.getName());
    private User currentUser;
    private Toko currentRestoran;
    private JPanel menuContainer;
    private JScrollPane scrollPane;
    private AuthService auth = new AuthService();
    private ReviewService reviewService = new ReviewService(); // Tambahkan ini
    
    /**
     * Creates new form RestoranFrame
     */
    public RestoranFrame(User user, Toko restoran) {
        this.currentUser = user;
        this.currentRestoran = restoran;
        initComponents();
        setLocationRelativeTo(null);
        setupUI();
        loadMenuFromDatabase();
        haloNamaOutput.setCaretColor(new java.awt.Color(0, 0, 0, 0)); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoutButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        haloNamaOutput = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        backButton = new javax.swing.JButton();
        lihatReviewButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logoutButton.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JatoStyle/gui/logo_mini.png"))); // NOI18N

        haloNamaOutput.setEditable(false);
        haloNamaOutput.setBackground(new java.awt.Color(206, 220, 239));
        haloNamaOutput.setFont(new java.awt.Font("Bahnschrift", 1, 20)); // NOI18N
        haloNamaOutput.setForeground(new java.awt.Color(206, 220, 239));
        haloNamaOutput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        haloNamaOutput.setBorder(null);
        haloNamaOutput.setDisabledTextColor(new java.awt.Color(59, 31, 11));
        haloNamaOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                haloNamaOutputActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        lihatReviewButton.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        lihatReviewButton.setText("Lihat Review");
        lihatReviewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatReviewButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backButton)
                .addGap(59, 59, 59))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(haloNamaOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(logoutButton)
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lihatReviewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(haloNamaOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lihatReviewButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backButton)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        int confirm = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Apakah Anda yakin ingin logout?",
            "Konfirmasi Logout",
            javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            // tutup dashboard
            this.dispose();

            // buka lagi login frame
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new JatoStyle.gui.LoginFrame().setVisible(true);
                }
            });

            System.out.println("User logged out successfully");
        }
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void haloNamaOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_haloNamaOutputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_haloNamaOutputActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // tutup frame restoran
        this.dispose();
        // kembali ke dashboard user
        DashboardUserFrame dash = new DashboardUserFrame(currentUser);
        dash.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void lihatReviewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatReviewButtonActionPerformed
        LihatReviewFrame reviewFrame = new LihatReviewFrame(currentUser, currentRestoran, reviewService);
        reviewFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lihatReviewButtonActionPerformed
                                             
    
    private void setupUI() {
        // panggil applyTemplateStyles() sebelum initDynamicUI()
        applyTemplateStyles();
        initDynamicUI();
        haloNamaOutput.setText("Halo, " + currentUser.getNama() + "! Selamat datang di " + currentRestoran.getNamaRestoran());

        setSize(900, 600);
        setLocationRelativeTo(null);
    }
    
    private void applyTemplateStyles() {
    // Background utama [206,220,239]
    getContentPane().setBackground(new Color(206, 220, 239));
    setTitle(currentRestoran.getNamaRestoran() + " - JatoStyle");

    // styling untuk komponen header
    haloNamaOutput.setBackground(new Color(206, 220, 239));
    haloNamaOutput.setForeground(new Color(0, 51, 79)); // #00334F
    haloNamaOutput.setBorder(null);
    haloNamaOutput.setFont(new Font("Bahnschrift", Font.BOLD, 18));

    // styling tombol logout - warna #00334F
    logoutButton.setBackground(new Color(0, 51, 79)); // #00334F
    logoutButton.setForeground(new Color(206, 220, 239)); // #CEDCEF
    logoutButton.setFocusPainted(false);
    logoutButton.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
    logoutButton.setFont(new Font("Bahnschrift", Font.BOLD, 12));
    
    // styling tombol back - warna #95BDE2
    backButton.setBackground(new Color(149, 189, 226)); // #95BDE2
    backButton.setForeground(new Color(59, 31, 11)); // #3B1F0B
    backButton.setFocusPainted(false);
    backButton.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
    backButton.setFont(new Font("Bahnschrift", Font.BOLD, 12));

    // styling tombol lihat review - warna #00334F
    lihatReviewButton.setBackground(new Color(0, 51, 79)); // #00334F
    lihatReviewButton.setForeground(new Color(206, 220, 239)); // #CEDCEF
    lihatReviewButton.setFocusPainted(false);
    lihatReviewButton.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
    lihatReviewButton.setFont(new Font("Bahnschrift", Font.BOLD, 12));
    
    // Set ukuran frame yang lebih besar untuk menampung layout
    setSize(1000, 700); // Diperbesar dari 900x600
}
    
   private void initDynamicUI() {
    // menu container
    menuContainer = new JPanel();
    menuContainer.setBackground(new Color(206, 220, 239));
    menuContainer.setLayout(new BoxLayout(menuContainer, BoxLayout.Y_AXIS));
    menuContainer.setBorder(new EmptyBorder(15, 15, 15, 15));

    // scrollpane - perbesar untuk gambar
    jScrollPane1.setViewportView(menuContainer);
    jScrollPane1.setBorder(BorderFactory.createLineBorder(new Color(149, 189, 226), 2));
    jScrollPane1.getViewport().setBackground(new Color(206, 220, 239));
    jScrollPane1.setBackground(new Color(206, 220, 239));
    
    // Set viewport preferred size untuk konsistensi
    jScrollPane1.getViewport().setPreferredSize(new Dimension(800, 400));

    // scroll bar
    JScrollBar verticalBar = jScrollPane1.getVerticalScrollBar();
    verticalBar.setUnitIncrement(20);
    verticalBar.setBackground(new Color(206, 220, 239));
    verticalBar.setForeground(new Color(149, 189, 226));
    
    // Horizontal scroll bar (nonaktifkan)
    JScrollBar horizontalBar = jScrollPane1.getHorizontalScrollBar();
    horizontalBar.setEnabled(false);
}
    
    private void loadMenuFromDatabase() {
    if (menuContainer == null) return;
    menuContainer.removeAll();

    try {
        // Update query untuk mengambil kolom gambar
        String sql = "SELECT *, " +
                    "CASE " +
                    "   WHEN gambar IS NOT NULL THEN 'ADA' " +
                    "   ELSE 'TIDAK ADA' " +
                    "END AS status_gambar " +
                    "FROM menu WHERE id_restoran = " + currentRestoran.getIdRestoran() + 
                    " ORDER BY nama_menu";
        
        System.out.println("Executing SQL: " + sql);

        ResultSet rs = auth.getKonektor().getData(sql);

        boolean any = false;
        int count = 0;
        while (rs != null && rs.next()) {
            any = true;
            count++;
            int idMenu = rs.getInt("id_menu");
            String nama = rs.getString("nama_menu");
            int harga = rs.getInt("harga");
            int stok = rs.getInt("stok");
            boolean statusHabis = rs.getBoolean("status_habis");
            
            // Load gambar dari database (BLOB)
            ImageIcon imageIcon = null;
            try {
                java.sql.Blob blob = rs.getBlob("gambar");
                if (blob != null) {
                    byte[] imageData = blob.getBytes(1, (int) blob.length());
                    ImageIcon icon = new ImageIcon(imageData);
                    // Resize gambar untuk tampilan
                    Image image = icon.getImage();
                    Image scaledImage = image.getScaledInstance(80, 80, Image.SCALE_SMOOTH);
                    imageIcon = new ImageIcon(scaledImage);
                    System.out.println("Gambar ditemukan untuk menu: " + nama);
                }
            } catch (Exception e) {
                System.out.println("Tidak ada gambar untuk menu: " + nama);
            }

            System.out.println("Menu found: " + nama + " - Rp " + harga + " - Stok: " + stok);

            JPanel card = createMenuCard(idMenu, nama, harga, stok, statusHabis, imageIcon);
            menuContainer.add(card);
            menuContainer.add(Box.createVerticalStrut(10));
        }

        System.out.println("Total menus loaded: " + count);

        if (!any) {
            JPanel messagePanel = new JPanel(new BorderLayout());
            messagePanel.setBackground(new Color(206, 220, 239)); // DIUBAH
            JLabel l = new JLabel("Tidak ada menu tersedia.");
            l.setFont(new Font("Bahnschrift", Font.PLAIN, 14));
            l.setForeground(new Color(128, 128, 128)); // Abu-abu
            l.setHorizontalAlignment(SwingConstants.CENTER);
            messagePanel.add(l, BorderLayout.CENTER);
            menuContainer.add(messagePanel);
        }

    } catch (Exception e) {
        System.out.println("Load menu error: " + e.getMessage());
        e.printStackTrace();
        JPanel messagePanel = new JPanel(new BorderLayout());
        messagePanel.setBackground(new Color(206, 220, 239)); // DIUBAH
        JLabel l = new JLabel("Error: Tidak dapat memuat menu dari database");
        l.setFont(new Font("Bahnschrift", Font.BOLD, 14));
        l.setForeground(Color.RED);
        l.setHorizontalAlignment(SwingConstants.CENTER);
        messagePanel.add(l, BorderLayout.CENTER);
        menuContainer.add(l, BorderLayout.CENTER);
    }

    menuContainer.revalidate();
    menuContainer.repaint();
}
    
    private JPanel createMenuCard(int idMenu, String namaMenu, int harga, int stok, boolean statusHabis, ImageIcon imageIcon) {
    JPanel card = new JPanel(new BorderLayout(10, 0)) {
        @Override
        protected void paintComponent(Graphics g) {
            Graphics2D g2 = (Graphics2D) g;
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            g2.setColor(Color.WHITE);
            g2.fillRoundRect(0, 0, getWidth(), getHeight(), 20, 20);
            g2.setColor(new Color(149, 189, 226)); // #95BDE2 - DIUBAH
            g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 20, 20);
        }
    };
    card.setOpaque(false);
    card.setBorder(new EmptyBorder(15, 20, 15, 20));
    card.setMaximumSize(new Dimension(Integer.MAX_VALUE, 140)); // Diperbesar untuk gambar

    // Panel kiri untuk gambar (100px fixed width)
    JPanel leftImagePanel = new JPanel(new BorderLayout());
    leftImagePanel.setOpaque(false);
    leftImagePanel.setPreferredSize(new Dimension(100, 100));
    leftImagePanel.setMinimumSize(new Dimension(100, 100));
    leftImagePanel.setMaximumSize(new Dimension(100, 100));
    leftImagePanel.setBorder(new EmptyBorder(5, 5, 5, 15));
    
    if (imageIcon != null) {
        // Tampilkan gambar
        JLabel imageLabel = new JLabel(imageIcon);
        imageLabel.setBorder(BorderFactory.createLineBorder(new Color(149, 189, 226), 2));
        imageLabel.setHorizontalAlignment(SwingConstants.CENTER);
        leftImagePanel.add(imageLabel, BorderLayout.CENTER);
    } else {
        // Tampilkan placeholder jika tidak ada gambar
        JPanel placeholderPanel = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                Graphics2D g2 = (Graphics2D) g;
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(new Color(240, 240, 240));
                g2.fillRect(0, 0, getWidth(), getHeight());
                
                // Gambar ikon kamera
                g2.setColor(new Color(200, 200, 200));
                int centerX = getWidth() / 2;
                int centerY = getHeight() / 2;
                
                // Lingkaran
                g2.drawOval(centerX - 25, centerY - 25, 50, 50);
                
                // Persegi (badan kamera)
                g2.drawRect(centerX - 15, centerY - 15, 30, 20);
                
                // Dot (lensa)
                g2.fillOval(centerX - 5, centerY - 5, 10, 10);
            }
        };
        placeholderPanel.setBorder(BorderFactory.createLineBorder(new Color(149, 189, 226), 1));
        placeholderPanel.setOpaque(false);
        
        JLabel noImageLabel = new JLabel("No Image", SwingConstants.CENTER);
        noImageLabel.setFont(new Font("Bahnschrift", Font.PLAIN, 10));
        noImageLabel.setForeground(new Color(150, 150, 150));
        
        JPanel placeholderContainer = new JPanel(new BorderLayout());
        placeholderContainer.setBackground(new Color(240, 240, 240));
        placeholderContainer.add(placeholderPanel, BorderLayout.CENTER);
        placeholderContainer.add(noImageLabel, BorderLayout.SOUTH);
        
        leftImagePanel.add(placeholderContainer, BorderLayout.CENTER);
    }

    // Panel tengah untuk info menu - Menggunakan GridBagLayout untuk alignment yang tepat
    JPanel centerPanel = new JPanel(new GridBagLayout());
    centerPanel.setOpaque(false);
    centerPanel.setBorder(new EmptyBorder(5, 10, 5, 10));
    
    GridBagConstraints gbc = new GridBagConstraints();
    gbc.fill = GridBagConstraints.HORIZONTAL;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.weightx = 1.0;
    gbc.gridwidth = GridBagConstraints.REMAINDER;

    // Nama Menu - menggunakan HTML untuk wrap text jika panjang
    String displayName = namaMenu.length() > 30 ? 
        "<html>" + namaMenu.substring(0, 30) + "...</html>" : namaMenu;
    
    JLabel lblNama = new JLabel(displayName);
    lblNama.setFont(new Font("Bahnschrift", Font.BOLD, 16));
    lblNama.setForeground(new Color(0, 51, 79)); // #00334F
    gbc.gridx = 0;
    gbc.gridy = 0;
    gbc.insets = new Insets(0, 0, 8, 0); // Bottom margin 8px
    centerPanel.add(lblNama, gbc);

    // Harga - format dengan titik pemisah ribuan
    JLabel lblHarga = new JLabel("Rp " + String.format("%,d", harga));
    lblHarga.setFont(new Font("Bahnschrift", Font.PLAIN, 14));
    lblHarga.setForeground(new Color(0, 51, 79)); // #00334F
    gbc.gridy = 1;
    gbc.insets = new Insets(0, 0, 8, 0); // Bottom margin 8px
    centerPanel.add(lblHarga, gbc);

    // Panel stok - dengan layout yang konsisten
    JPanel stokPanel = createStokPanel(stok);
    gbc.gridy = 2;
    gbc.insets = new Insets(0, 0, 0, 0); // No margin
    centerPanel.add(stokPanel, gbc);

    // Panel kanan untuk tombol - menggunakan BoxLayout untuk alignment vertikal
    JPanel rightPanel = new JPanel();
    rightPanel.setOpaque(false);
    rightPanel.setLayout(new BoxLayout(rightPanel, BoxLayout.Y_AXIS));
    rightPanel.setBorder(new EmptyBorder(0, 20, 0, 0)); // Margin kiri 20px
    rightPanel.setPreferredSize(new Dimension(160, 100)); // Fixed width untuk konsistensi

    // Panel untuk tombol - menggunakan FlowLayout dengan alignment kanan
    JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT, 0, 0));
    buttonPanel.setOpaque(false);
    buttonPanel.setMaximumSize(new Dimension(160, 40));
    
    JButton addToCartBtn = new JButton("Tambah Keranjang");
    addToCartBtn.setFont(new Font("Bahnschrift", Font.BOLD, 12));
    addToCartBtn.setFocusPainted(false);
    addToCartBtn.setPreferredSize(new Dimension(150, 35));
    
    // cek stok
    if (stok > 0) {
        // MASIH ADA STOK → ENABLE
        addToCartBtn.setBackground(new Color(0, 51, 79)); // #00334F (dikembalikan ke warna semula)
        addToCartBtn.setForeground(new Color(206, 220, 239)); // #CEDCEF (dikembalikan ke warna semula)
        addToCartBtn.setEnabled(true);
        addToCartBtn.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15)); // Border kosong (dikembalikan ke semula)

        addToCartBtn.addActionListener(e -> {
            addToCart(idMenu, namaMenu, harga);
        });

    } else {
        // habis → disable
        addToCartBtn.setBackground(Color.GRAY);
        addToCartBtn.setForeground(Color.WHITE);
        addToCartBtn.setEnabled(false);
        addToCartBtn.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        addToCartBtn.setText("Stok Habis");
    }
    
    buttonPanel.add(addToCartBtn);
    
    // Tambahkan vertical glue untuk mendorong tombol ke atas
    rightPanel.add(Box.createVerticalGlue());
    rightPanel.add(buttonPanel);
    rightPanel.add(Box.createVerticalGlue());

    // Atur semua komponen ke card
    card.add(leftImagePanel, BorderLayout.WEST);
    card.add(centerPanel, BorderLayout.CENTER);
    card.add(rightPanel, BorderLayout.EAST);

    return card;
}

private JPanel createStokPanel(int stok) {
    JPanel panel = new JPanel(new FlowLayout(FlowLayout.CENTER, 0, 0)) { // Diubah dari LEFT ke CENTER
        @Override
        protected void paintComponent(Graphics g) {
            Graphics2D g2 = (Graphics2D) g;
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            
            // Warna background berdasarkan jumlah stok
            Color bgColor;
            if (stok <= 0) {
                bgColor = new Color(255, 204, 204); // Merah muda untuk stok habis
            } else if (stok <= 5) {
                bgColor = new Color(255, 229, 204); // Orange untuk stok menipis
            } else {
                bgColor = new Color(204, 229, 255); // Biru muda untuk stok cukup
            }
            
            g2.setColor(bgColor);
            g2.fillRoundRect(0, 0, getWidth(), getHeight(), 8, 8);
            
            // Border
            g2.setColor(new Color(149, 189, 226)); // #95BDE2
            g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 8, 8);
        }
    };
    
    panel.setOpaque(false);
    panel.setPreferredSize(new Dimension(120, 25));
    panel.setMaximumSize(new Dimension(120, 25));
    panel.setMinimumSize(new Dimension(120, 25));
    
    // Label stok dengan alignment tengah
    JLabel stokLabel = new JLabel();
    stokLabel.setFont(new Font("Bahnschrift", Font.BOLD, 12));
    stokLabel.setHorizontalAlignment(SwingConstants.CENTER); // Diubah ke CENTER
    
    // Warna teks berdasarkan stok
    if (stok <= 0) {
        stokLabel.setForeground(new Color(204, 0, 0)); // Merah untuk stok habis
        stokLabel.setText("Stok: HABIS");
    } else if (stok <= 5) {
        stokLabel.setForeground(new Color(153, 76, 0)); // Coklat untuk stok menipis
        stokLabel.setText("Stok: " + stok + " (Menipis)");
    } else {
        stokLabel.setForeground(new Color(0, 51, 79)); // #00334F untuk stok cukup
        stokLabel.setText("Stok: " + stok);
    }
    
    // Padding untuk teks (dihapus padding kiri yang sebelumnya ada)
    stokLabel.setBorder(new EmptyBorder(0, 0, 0, 0)); // Diubah dari (0,10,0,0)
    panel.add(stokLabel);
    
    return panel;
}
    
    private void addToCart(int idMenu, String namaMenu, int harga) {
        try {
            // cek jika item sudah di keranjang
            String checkSql = "SELECT * FROM keranjang WHERE id_user = " + currentUser.getIdUser() + 
                            " AND id_menu = " + idMenu + " AND status_checkout = 0";
            ResultSet checkRs = auth.getKonektor().getData(checkSql);
            
            if (checkRs != null && checkRs.next()) {
                // update jumlah
                int currentQty = checkRs.getInt("jumlah");
                String updateSql = "UPDATE keranjang SET jumlah = " + (currentQty + 1) + 
                                 " WHERE id_keranjang = " + checkRs.getInt("id_keranjang");
                auth.getKonektor().query(updateSql);
            } else {
                // insert item baru
                String insertSql = "INSERT INTO keranjang (id_user, id_menu, jumlah, catatan, status_checkout) " +
                                 "VALUES (" + currentUser.getIdUser() + ", " + idMenu + ", 1, '', 0)";
                auth.getKonektor().query(insertSql);
            }

            JOptionPane.showMessageDialog(this, 
                namaMenu + " berhasil ditambahkan ke keranjang!", 
                "Sukses", 
                JOptionPane.INFORMATION_MESSAGE);
                
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                "Gagal menambahkan ke keranjang: " + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            javax.swing.JOptionPane.showMessageDialog(null, 
                "RestoranFrame harus dibuka melalui DashboardUserFrame setelah login user.", 
                "Informasi", 
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextField haloNamaOutput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lihatReviewButton;
    private javax.swing.JButton logoutButton;
    // End of variables declaration//GEN-END:variables
}
