/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JatoStyle.gui;

import JatoStyle.models.Restoran;
import JatoStyle.models.User;
import JatoStyle.services.AuthService;
import java.awt.*;
import java.sql.ResultSet;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import javax.swing.border.Border;
import JatoStyle.services.ReviewService;
import JatoStyle.models.Review;

public class RestoranFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RestoranFrame.class.getName());
    private User currentUser;
    private Restoran currentRestoran;
    private JPanel menuContainer;
    private JScrollPane scrollPane;
    private AuthService auth = new AuthService();
    private ReviewService reviewService = new ReviewService(); // Tambahkan ini
    
    /**
     * Creates new form RestoranFrame
     */
    public RestoranFrame(User user, Restoran restoran) {
        this.currentUser = user;
        this.currentRestoran = restoran;
        initComponents();
        setLocationRelativeTo(null);
        setupUI();
        loadMenuFromDatabase();
        haloNamaOutput.setCaretColor(new java.awt.Color(0, 0, 0, 0)); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        profilButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        haloNamaOutput = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        backButton = new javax.swing.JButton();
        lihatReviewButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        profilButton.setText("👤");
        profilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilButtonActionPerformed(evt);
            }
        });

        logoutButton.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JatoStyle/gui/dashboardlogo.png"))); // NOI18N

        haloNamaOutput.setEditable(false);
        haloNamaOutput.setBackground(new java.awt.Color(250, 240, 227));
        haloNamaOutput.setFont(new java.awt.Font("Bahnschrift", 1, 20)); // NOI18N
        haloNamaOutput.setForeground(new java.awt.Color(250, 240, 227));
        haloNamaOutput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        haloNamaOutput.setBorder(null);
        haloNamaOutput.setDisabledTextColor(new java.awt.Color(59, 31, 11));
        haloNamaOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                haloNamaOutputActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        lihatReviewButton.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        lihatReviewButton.setText("Lihat Review");
        lihatReviewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatReviewButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backButton)
                .addGap(59, 59, 59))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(haloNamaOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(logoutButton)
                        .addGap(22, 22, 22)
                        .addComponent(profilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lihatReviewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(haloNamaOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(profilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lihatReviewButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backButton)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void profilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilButtonActionPerformed
        ProfileFrame pf = new ProfileFrame(currentUser, this); // kirim data user + frame dashboard
        pf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_profilButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        int confirm = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Apakah Anda yakin ingin logout?",
            "Konfirmasi Logout",
            javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            // tutup dashboard
            this.dispose();

            // buka lagi login frame
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new JatoStyle.gui.LoginFrame().setVisible(true);
                }
            });

            System.out.println("User logged out successfully");
        }
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void haloNamaOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_haloNamaOutputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_haloNamaOutputActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // tutup frame restoran
        this.dispose();
        // kembali ke dashboard user
        DashboardUserFrame dash = new DashboardUserFrame(currentUser);
        dash.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void lihatReviewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatReviewButtonActionPerformed
        LihatReviewFrame reviewFrame = new LihatReviewFrame(currentUser, currentRestoran, reviewService);
        reviewFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lihatReviewButtonActionPerformed
                                             
    
    private void setupUI() {
        // panggil applyTemplateStyles() sebelum initDynamicUI()
        applyTemplateStyles();
        initDynamicUI();
        haloNamaOutput.setText("Halo, " + currentUser.getNama() + "! Selamat datang di " + currentRestoran.getNamaRestoran());

        setSize(900, 600);
        setLocationRelativeTo(null);
    }
    
    private void applyTemplateStyles() {
        getContentPane().setBackground(new Color(250, 240, 227)); // #FAF0E3
        setTitle(currentRestoran.getNamaRestoran() + " - FoodOrder");

        // styling untuk komponen header
        haloNamaOutput.setBackground(new Color(250, 240, 227));
        haloNamaOutput.setForeground(new Color(59, 31, 11)); 
        haloNamaOutput.setBorder(null);
        haloNamaOutput.setFont(new Font("Bahnschrift", Font.BOLD, 18));

        // styling tombol profil
        profilButton.setBackground(new Color(241, 124, 42)); // #F17C2A
        profilButton.setForeground(Color.WHITE);
        profilButton.setFocusPainted(false);
        profilButton.setBorder(BorderFactory.createEmptyBorder(8, 8, 8, 8));
        profilButton.setFont(new Font("Bahnschrift", Font.BOLD, 14));

        // styling tombol logout
        logoutButton.setBackground(new Color(229, 75, 31)); // #E54B1F
        logoutButton.setForeground(Color.WHITE);
        logoutButton.setFocusPainted(false);
        logoutButton.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        logoutButton.setFont(new Font("Bahnschrift", Font.BOLD, 12));
        
        // styling tombol back
        backButton.setBackground(new Color(241, 124, 42)); // warna orange seperti tombol lain
        backButton.setForeground(Color.WHITE);
        backButton.setFocusPainted(false);
        backButton.setBorder(
            BorderFactory.createEmptyBorder(8, 15, 8, 15)
        );
        backButton.setFont(new Font("Bahnschrift", Font.BOLD, 12));

    }
    
    private void initDynamicUI() {
        // menu container
        menuContainer = new JPanel();
        menuContainer.setBackground(new Color(250, 240, 227));
        menuContainer.setLayout(new BoxLayout(menuContainer, BoxLayout.Y_AXIS));
        menuContainer.setBorder(new EmptyBorder(15, 15, 15, 15));

        // scrollpane
        jScrollPane1.setViewportView(menuContainer);
        jScrollPane1.setBorder(BorderFactory.createLineBorder(new Color(229, 75, 31), 1));
        jScrollPane1.getViewport().setBackground(new Color(250, 240, 227));
        jScrollPane1.setBackground(new Color(250, 240, 227));

        // scroll bar
        JScrollBar verticalBar = jScrollPane1.getVerticalScrollBar();
        verticalBar.setUnitIncrement(16);
        verticalBar.setBackground(new Color(250, 240, 227));
        verticalBar.setForeground(new Color(241, 124, 42));
    }


    
    private void loadMenuFromDatabase() {
        if (menuContainer == null) return;
        menuContainer.removeAll();

        try {
            String sql = "SELECT * FROM menu WHERE id_restoran = " + currentRestoran.getIdRestoran() + " ORDER BY nama_menu";
            System.out.println("Executing SQL: " + sql); // DEBUG

            ResultSet rs = auth.getKonektor().getData(sql);

            boolean any = false;
            int count = 0;
            while (rs != null && rs.next()) {
                any = true;
                count++;
                int idMenu = rs.getInt("id_menu");
                String nama = rs.getString("nama_menu");
                int harga = rs.getInt("harga");
                int stok = rs.getInt("stok");
                boolean statusHabis = rs.getBoolean("status_habis");

                System.out.println("Menu found: " + nama + " - Rp " + harga + " - Stok: " + stok); // DEBUG

                JPanel card = createMenuCard(idMenu, nama, harga, stok, statusHabis);
                menuContainer.add(card);
                menuContainer.add(Box.createVerticalStrut(10));
            }

            System.out.println("Total menus loaded: " + count); // DEBUG

            if (!any) {
                JPanel messagePanel = new JPanel(new BorderLayout());
                messagePanel.setOpaque(false);
                JLabel l = new JLabel("Tidak ada menu tersedia.");
                l.setFont(new Font("Bahnschrift", Font.PLAIN, 14));
                l.setForeground(new Color(120, 120, 120));
                l.setHorizontalAlignment(SwingConstants.CENTER);
                messagePanel.add(l, BorderLayout.CENTER);
                menuContainer.add(messagePanel);
            }

        } catch (Exception e) {
            System.out.println("Load menu error: " + e.getMessage());
            e.printStackTrace();
            JPanel messagePanel = new JPanel(new BorderLayout());
            messagePanel.setOpaque(false);
            JLabel l = new JLabel("Error: Tidak dapat memuat menu dari database");
            l.setFont(new Font("Bahnschrift", Font.BOLD, 14));
            l.setForeground(Color.RED);
            l.setHorizontalAlignment(SwingConstants.CENTER);
            menuContainer.add(l, BorderLayout.CENTER);
        }

        menuContainer.revalidate();
        menuContainer.repaint();
    }
    
    private JPanel createMenuCard(int idMenu, String namaMenu, int harga, int stok, boolean statusHabis) {
        JPanel card = new JPanel(new BorderLayout()) {
            @Override
            protected void paintComponent(Graphics g) {
                Graphics2D g2 = (Graphics2D) g;
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(Color.WHITE);
                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 20, 20);
                g2.setColor(new Color(229, 75, 31)); // #E54B1F
                g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 20, 20);
            }
        };
        card.setOpaque(false);
        card.setBorder(new EmptyBorder(15, 20, 15, 20));
        card.setMaximumSize(new Dimension(Integer.MAX_VALUE, 100)); // AUTO FOLLOW WIDTH

        JPanel left = new JPanel();
        left.setOpaque(false);
        left.setLayout(new BoxLayout(left, BoxLayout.Y_AXIS));
        left.setBorder(new EmptyBorder(5, 10, 5, 10));

        JLabel lblNama = new JLabel(namaMenu);
        lblNama.setFont(new Font("Bahnschrift", Font.BOLD, 16));
        lblNama.setForeground(new Color(59, 31, 11));

        JLabel lblHarga = new JLabel("Rp " + String.format("%,d", harga));
        lblHarga.setFont(new Font("Bahnschrift", Font.PLAIN, 14));
        lblHarga.setForeground(new Color(59, 31, 11));

        left.add(lblNama);
        left.add(Box.createVerticalStrut(5));
        left.add(lblHarga);

        JPanel right = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        right.setOpaque(false);
        right.setBorder(new EmptyBorder(0, 0, 0, 10));

        JButton addToCartBtn = new JButton("Tambah Keranjang");
        addToCartBtn.setFont(new Font("Bahnschrift", Font.BOLD, 12));
        addToCartBtn.setFocusPainted(false);
        addToCartBtn.setPreferredSize(new Dimension(150, 35));
        addToCartBtn.setBorder(
            BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(new Color(229, 75, 31), 1),
                BorderFactory.createEmptyBorder(8, 15, 8, 15)
            )
        );

        // cek stok
        if (stok > 0) {
            // MASIH ADA STOK → ENABLE
            addToCartBtn.setBackground(new Color(241, 124, 42)); // ORANGE
            addToCartBtn.setForeground(Color.WHITE);
            addToCartBtn.setEnabled(true);

            addToCartBtn.addActionListener(e -> {
                addToCart(idMenu, namaMenu, harga);
            });

        } else {
            // habis → disable
            addToCartBtn.setBackground(Color.GRAY);
            addToCartBtn.setForeground(Color.WHITE);
            addToCartBtn.setEnabled(false);
        }

        right.add(addToCartBtn);

        card.add(left, BorderLayout.WEST);
        card.add(right, BorderLayout.EAST);

        return card;
    }

    
    private void addToCart(int idMenu, String namaMenu, int harga) {
        try {
            // cek jika item sudah di keranjang
            String checkSql = "SELECT * FROM keranjang WHERE id_user = " + currentUser.getIdUser() + 
                            " AND id_menu = " + idMenu + " AND status_checkout = 0";
            ResultSet checkRs = auth.getKonektor().getData(checkSql);
            
            if (checkRs != null && checkRs.next()) {
                // update jumlah
                int currentQty = checkRs.getInt("jumlah");
                String updateSql = "UPDATE keranjang SET jumlah = " + (currentQty + 1) + 
                                 " WHERE id_keranjang = " + checkRs.getInt("id_keranjang");
                auth.getKonektor().query(updateSql);
            } else {
                // insert item baru
                String insertSql = "INSERT INTO keranjang (id_user, id_menu, jumlah, catatan, status_checkout) " +
                                 "VALUES (" + currentUser.getIdUser() + ", " + idMenu + ", 1, '', 0)";
                auth.getKonektor().query(insertSql);
            }

            JOptionPane.showMessageDialog(this, 
                namaMenu + " berhasil ditambahkan ke keranjang!", 
                "Sukses", 
                JOptionPane.INFORMATION_MESSAGE);
                
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                "Gagal menambahkan ke keranjang: " + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            javax.swing.JOptionPane.showMessageDialog(null, 
                "RestoranFrame harus dibuka melalui DashboardUserFrame setelah login user.", 
                "Informasi", 
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextField haloNamaOutput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lihatReviewButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton profilButton;
    // End of variables declaration//GEN-END:variables
}
